[package]
name = "goth_jems"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "2.9.1"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
grid = "0.18.0"
itertools = "0.14.0"
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"
